stages:
  - build
  - lint

build:
  tags:
    - host
  image: node:latest
  stage: build
  script:
    - npm install
    - npm run build

lint:
  tags:
    - host
  needs: ['build']
  image: node:latest
  stage: lint
  script:
    - npm install
    - npm run lint