stages:
  - build
  - lint
  - deploy

build:
  tags:
    - host
  image: node:latest
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
    when: on_success
  allow_failure: false

lint:
  tags:
    - host
  image: node:latest
  stage: lint
  script:
    - npm install
    - npm run lint
  allow_failure: false

deploy:
  tags:
    - host
  variables:
    CLOUDFLARE_API_TOKEN: $CLOUDFLARE_API_TOKEN
    CLOUDFLARE_ACCOUNT_ID: $CLOUDFLARE_ACCOUNT_ID
  needs: ['build', 'lint']
  image: node:latest
  stage: deploy
  environment:
    name: production
    url: https://master.pythsource.pages.dev
  script:
    - npm install
    - npm run build
    - npx wrangler pages deploy dist/ --project-name=pythsource